// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alerts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAlertRule = `-- name: CreateAlertRule :one
INSERT INTO alert_rules (instrument_id, rule_type, threshold, window_seconds, channel, target)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, instrument_id, rule_type, threshold, window_seconds, channel, target, is_enabled, created_at
`

type CreateAlertRuleParams struct {
	InstrumentID  int64
	RuleType      string
	Threshold     pgtype.Numeric
	WindowSeconds pgtype.Int4
	Channel       string
	Target        string
}

// Persists a new alerting rule and returns the stored row.
func (q *Queries) CreateAlertRule(ctx context.Context, arg CreateAlertRuleParams) (AlertRule, error) {
	row := q.db.QueryRow(ctx, createAlertRule,
		arg.InstrumentID,
		arg.RuleType,
		arg.Threshold,
		arg.WindowSeconds,
		arg.Channel,
		arg.Target,
	)
	var i AlertRule
	err := row.Scan(
		&i.ID,
		&i.InstrumentID,
		&i.RuleType,
		&i.Threshold,
		&i.WindowSeconds,
		&i.Channel,
		&i.Target,
		&i.IsEnabled,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAlertRule = `-- name: DeleteAlertRule :one
DELETE FROM alert_rules
WHERE id = $1
RETURNING id
`

// Deletes a rule by id, returning it so the caller can tell a real deletion from
// a missing id (no rows).
func (q *Queries) DeleteAlertRule(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, deleteAlertRule, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const insertAlertHistory = `-- name: InsertAlertHistory :one
INSERT INTO alert_history (rule_id, observed_value, delivery_status)
VALUES ($1, $2, $3)
RETURNING id, rule_id, fired_at, observed_value, delivery_status
`

type InsertAlertHistoryParams struct {
	RuleID         int64
	ObservedValue  pgtype.Numeric
	DeliveryStatus string
}

// Records a fired alert and the outcome of its notification delivery.
func (q *Queries) InsertAlertHistory(ctx context.Context, arg InsertAlertHistoryParams) (AlertHistory, error) {
	row := q.db.QueryRow(ctx, insertAlertHistory, arg.RuleID, arg.ObservedValue, arg.DeliveryStatus)
	var i AlertHistory
	err := row.Scan(
		&i.ID,
		&i.RuleID,
		&i.FiredAt,
		&i.ObservedValue,
		&i.DeliveryStatus,
	)
	return i, err
}

const listAlertRules = `-- name: ListAlertRules :many
SELECT id, instrument_id, rule_type, threshold, window_seconds, channel, target, is_enabled, created_at
FROM alert_rules
ORDER BY created_at DESC, id DESC
`

// Lists every alerting rule, newest first, for the management API.
func (q *Queries) ListAlertRules(ctx context.Context) ([]AlertRule, error) {
	rows, err := q.db.Query(ctx, listAlertRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertRule{}
	for rows.Next() {
		var i AlertRule
		if err := rows.Scan(
			&i.ID,
			&i.InstrumentID,
			&i.RuleType,
			&i.Threshold,
			&i.WindowSeconds,
			&i.Channel,
			&i.Target,
			&i.IsEnabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledAlertRules = `-- name: ListEnabledAlertRules :many
SELECT r.id, r.instrument_id, i.symbol, r.rule_type, r.threshold, r.window_seconds,
       r.channel, r.target, r.is_enabled, r.created_at
FROM alert_rules r
JOIN instruments i ON i.id = r.instrument_id
WHERE r.is_enabled
ORDER BY r.id
`

type ListEnabledAlertRulesRow struct {
	ID            int64
	InstrumentID  int64
	Symbol        string
	RuleType      string
	Threshold     pgtype.Numeric
	WindowSeconds pgtype.Int4
	Channel       string
	Target        string
	IsEnabled     bool
	CreatedAt     pgtype.Timestamptz
}

// Lists the enabled rules the Alerting service evaluates, joined to the symbol so
// the engine can match ticks by symbol without a second lookup.
func (q *Queries) ListEnabledAlertRules(ctx context.Context) ([]ListEnabledAlertRulesRow, error) {
	rows, err := q.db.Query(ctx, listEnabledAlertRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnabledAlertRulesRow{}
	for rows.Next() {
		var i ListEnabledAlertRulesRow
		if err := rows.Scan(
			&i.ID,
			&i.InstrumentID,
			&i.Symbol,
			&i.RuleType,
			&i.Threshold,
			&i.WindowSeconds,
			&i.Channel,
			&i.Target,
			&i.IsEnabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
