// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForInsertPrices implements pgx.CopyFromSource.
type iteratorForInsertPrices struct {
	rows                 []InsertPricesParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertPrices) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertPrices) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].InstrumentID,
		r.rows[0].Ts,
		r.rows[0].Price,
		r.rows[0].Volume,
		r.rows[0].Ma20,
		r.rows[0].Volatility,
	}, nil
}

func (r iteratorForInsertPrices) Err() error {
	return nil
}

// Bulk-inserts enriched price rows using the COPY protocol, the fastest path
// into the partitioned prices table.
func (q *Queries) InsertPrices(ctx context.Context, arg []InsertPricesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"prices"}, []string{"instrument_id", "ts", "price", "volume", "ma_20", "volatility"}, &iteratorForInsertPrices{rows: arg})
}
