// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: instruments.sql

package sqlc

import (
	"context"
)

const upsertInstrument = `-- name: UpsertInstrument :one
INSERT INTO instruments (symbol, base_asset, quote_asset, source)
VALUES ($1, $2, $3, $4)
ON CONFLICT (symbol) DO UPDATE SET updated_at = now()
RETURNING id
`

type UpsertInstrumentParams struct {
	Symbol     string
	BaseAsset  string
	QuoteAsset string
	Source     string
}

// Inserts an instrument or returns the existing one's id, keyed by symbol.
func (q *Queries) UpsertInstrument(ctx context.Context, arg UpsertInstrumentParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertInstrument,
		arg.Symbol,
		arg.BaseAsset,
		arg.QuoteAsset,
		arg.Source,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
