// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Instrument struct {
	ID         int64
	Symbol     string
	BaseAsset  string
	QuoteAsset string
	Source     string
	IsActive   bool
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Price struct {
	InstrumentID int64
	Ts           pgtype.Timestamptz
	Price        pgtype.Numeric
	Volume       pgtype.Numeric
	Ma20         pgtype.Numeric
	Volatility   pgtype.Numeric
	IngestedAt   pgtype.Timestamptz
}

type PricesDefault struct {
	InstrumentID int64
	Ts           pgtype.Timestamptz
	Price        pgtype.Numeric
	Volume       pgtype.Numeric
	Ma20         pgtype.Numeric
	Volatility   pgtype.Numeric
	IngestedAt   pgtype.Timestamptz
}

// Shareable Playground queries, addressed by a non-enumerable UUID.
type SavedQuery struct {
	ID          pgtype.UUID
	Title       pgtype.Text
	SqlText     string
	ChartConfig []byte
	CreatedAt   pgtype.Timestamptz
}
