// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: prices.sql

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type InsertPricesParams struct {
	InstrumentID int64
	Ts           pgtype.Timestamptz
	Price        pgtype.Numeric
	Volume       pgtype.Numeric
	Ma20         pgtype.Numeric
	Volatility   pgtype.Numeric
}
