// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Persists a new alerting rule and returns the stored row.
	CreateAlertRule(ctx context.Context, arg CreateAlertRuleParams) (AlertRule, error)
	// Persists a Playground query and returns the stored row, including its
	// generated id and timestamp, so the caller can build the share URL.
	CreateSavedQuery(ctx context.Context, arg CreateSavedQueryParams) (SavedQuery, error)
	// Deletes a rule by id, returning it so the caller can tell a real deletion from
	// a missing id (no rows).
	DeleteAlertRule(ctx context.Context, id int64) (int64, error)
	// Deletes an instrument's price rows within the half-open range [from, to).
	// Backs the historical seeder's idempotent per-window replace.
	DeletePricesInRange(ctx context.Context, arg DeletePricesInRangeParams) (int64, error)
	// Returns up to limit price values strictly before a timestamp for an
	// instrument, most recent first. Warms the seeder's rolling window so the
	// derived indicators stay continuous regardless of which range a run seeds.
	// Backed by the (instrument_id, ts DESC) index.
	GetClosesBefore(ctx context.Context, arg GetClosesBeforeParams) ([]pgtype.Numeric, error)
	// Returns the full instrument row for a symbol, or no rows if it is unknown.
	GetInstrumentBySymbol(ctx context.Context, symbol string) (Instrument, error)
	// Returns the most recent price observation for an instrument. Backed by the
	// (instrument_id, ts DESC) index, which is walked backwards without a sort.
	GetLatestPrice(ctx context.Context, instrumentID int64) (GetLatestPriceRow, error)
	// Returns an instrument's price observations within the half-open range
	// [from, to), returned oldest first. When more rows exist than the caller's
	// limit, the most RECENT ones are kept (the inner query walks the
	// (instrument_id, ts DESC) index backwards and takes the newest limit rows),
	// then the outer query re-sorts them ascending for the response.
	GetPriceSeries(ctx context.Context, arg GetPriceSeriesParams) ([]GetPriceSeriesRow, error)
	// Loads a saved query by its UUID, or no rows if the id is unknown.
	GetSavedQuery(ctx context.Context, id pgtype.UUID) (SavedQuery, error)
	// Records a fired alert and the outcome of its notification delivery.
	InsertAlertHistory(ctx context.Context, arg InsertAlertHistoryParams) (AlertHistory, error)
	// Bulk-inserts enriched price rows using the COPY protocol, the fastest path
	// into the partitioned prices table.
	InsertPrices(ctx context.Context, arg []InsertPricesParams) (int64, error)
	// Lists every alerting rule (enabled or not), newest first, joined to its symbol
	// for the management API.
	ListAlertRules(ctx context.Context) ([]ListAlertRulesRow, error)
	// Lists the enabled rules the Alerting service evaluates, joined to the symbol so
	// the engine can match ticks by symbol without a second lookup.
	ListEnabledAlertRules(ctx context.Context) ([]ListEnabledAlertRulesRow, error)
	// Lists every instrument, ordered by symbol for a stable response.
	ListInstruments(ctx context.Context) ([]Instrument, error)
	// Inserts an instrument or returns the existing one's id, keyed by symbol.
	UpsertInstrument(ctx context.Context, arg UpsertInstrumentParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
