// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	// Bulk-inserts enriched price rows using the COPY protocol, the fastest path
	// into the partitioned prices table.
	InsertPrices(ctx context.Context, arg []InsertPricesParams) (int64, error)
	// Inserts an instrument or returns the existing one's id, keyed by symbol.
	UpsertInstrument(ctx context.Context, arg UpsertInstrumentParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
