// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: saved_queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSavedQuery = `-- name: CreateSavedQuery :one
INSERT INTO saved_queries (title, sql_text, chart_config)
VALUES ($1, $2, $3)
RETURNING id, title, sql_text, chart_config, created_at
`

type CreateSavedQueryParams struct {
	Title       pgtype.Text
	SqlText     string
	ChartConfig []byte
}

// Persists a Playground query and returns the stored row, including its
// generated id and timestamp, so the caller can build the share URL.
func (q *Queries) CreateSavedQuery(ctx context.Context, arg CreateSavedQueryParams) (SavedQuery, error) {
	row := q.db.QueryRow(ctx, createSavedQuery, arg.Title, arg.SqlText, arg.ChartConfig)
	var i SavedQuery
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.SqlText,
		&i.ChartConfig,
		&i.CreatedAt,
	)
	return i, err
}

const getSavedQuery = `-- name: GetSavedQuery :one
SELECT id, title, sql_text, chart_config, created_at
FROM saved_queries
WHERE id = $1
`

// Loads a saved query by its UUID, or no rows if the id is unknown.
func (q *Queries) GetSavedQuery(ctx context.Context, id pgtype.UUID) (SavedQuery, error) {
	row := q.db.QueryRow(ctx, getSavedQuery, id)
	var i SavedQuery
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.SqlText,
		&i.ChartConfig,
		&i.CreatedAt,
	)
	return i, err
}
